insulate("Missions:scan()", function()

    require "init"
    require "spec.mocks"
    require "spec.asserts"

    local player = PlayerSpaceship()

    it("should create a valid Mission with one ship", function()
        local mission = Missions:scan(CpuShip())

        assert.is_true(Mission:isMission(mission))
    end)
    it("should create a valid Mission with multiple ships", function()
        local thing1 = CpuShip()
        local thing2 = CpuShip()
        local thing3 = CpuShip()
        local mission = Missions:scan({thing1, thing2, thing3})
        assert.is_true(Mission:isMission(mission))
        mission:setPlayer(player)
        mission:accept()
        mission:start()

        assert.contains_value(thing1, mission:getTargets())
        assert.contains_value(thing2, mission:getTargets())
        assert.contains_value(thing3, mission:getTargets())
    end)
    it("should create a valid Mission with multiple asteroids", function()
        local thing1 = Asteroid()
        local thing2 = Asteroid()
        local thing3 = Asteroid()
        local mission = Missions:scan({thing1, thing2, thing3})
        assert.is_true(Mission:isMission(mission))
        mission:setPlayer(player)
        mission:accept()
        mission:start()

        assert.contains_value(thing1, mission:getTargets())
        assert.contains_value(thing2, mission:getTargets())
        assert.contains_value(thing3, mission:getTargets())
    end)
    it("should create a valid Mission with mixed objects", function()
        local thing1 = SpaceStation()
        local thing2 = CpuShip()
        local thing3 = Asteroid()
        local mission = Missions:scan({thing1, thing2, thing3})
        assert.is_true(Mission:isMission(mission))
        mission:setPlayer(player)
        mission:accept()
        mission:start()

        assert.contains_value(thing1, mission:getTargets())
        assert.contains_value(thing2, mission:getTargets())
        assert.contains_value(thing3, mission:getTargets())
    end)
    it("fails if the first parameter is not given", function()
        assert.has_error(function() Missions:scan() end)
    end)
    it("should create a valid Mission if a callback function is given that returns one ship", function()
        local ship = CpuShip()
        local mission = Missions:scan(function() return ship end)
        assert.is_true(Mission:isMission(mission))
        mission:setPlayer(player)
        mission:accept()
        mission:start()

        assert.is_same({ship}, mission:getTargets())
    end)
    it("should create a valid Mission if a callback function is given that returns multiple ships", function()
        local thing1 = CpuShip()
        local thing2 = CpuShip()
        local thing3 = CpuShip()
        local mission = Missions:scan(function() return {thing1, thing2, thing3} end)
        assert.is_true(Mission:isMission(mission))
        mission:setPlayer(player)
        mission:accept()
        mission:start()

        assert.contains_value(thing1, mission:getTargets())
        assert.contains_value(thing2, mission:getTargets())
        assert.contains_value(thing3, mission:getTargets())
    end)
    it("should create a valid Mission if a callback function is given that returns multiple asteroids", function()
        local thing1 = Asteroid()
        local thing2 = Asteroid()
        local thing3 = Asteroid()
        local mission = Missions:scan(function() return {thing1, thing2, thing3} end)
        assert.is_true(Mission:isMission(mission))
        mission:setPlayer(player)
        mission:accept()
        mission:start()

        assert.contains_value(thing1, mission:getTargets())
        assert.contains_value(thing2, mission:getTargets())
        assert.contains_value(thing3, mission:getTargets())
    end)
    it("should create a valid Mission if a callback function is given that returns multiple mixed objects", function()
        local thing1 = SpaceStation()
        local thing2 = CpuShip()
        local thing3 = Asteroid()
        local mission = Missions:scan(function() return {thing1, thing2, thing3} end)
        assert.is_true(Mission:isMission(mission))
        mission:setPlayer(player)
        mission:accept()
        mission:start()

        assert.contains_value(thing1, mission:getTargets())
        assert.contains_value(thing2, mission:getTargets())
        assert.contains_value(thing3, mission:getTargets())
    end)
    it("fails if a call back function is given that returns nil", function()
        local mission = Missions:scan(function() return nil end)
        mission:setPlayer(player)
        mission:accept()

        assert.has_error(function()
            mission:start()
        end)
    end)
    it("fails if no player was set", function()
        local mission = Missions:scan(CpuShip())

        assert.has_error(function()
            mission:accept()
            mission:start()
        end)
    end)

    it("fails if second parameter is a number", function()
        assert.has_error(function() Missions:scan(CpuShip(), 3) end)
    end)

    describe("config.scan", function()
        it("can be set to \"fof\", \"simple\" or \"full\" for ships", function()
            Missions:scan(CpuShip(), {scan = "fof"})
            Missions:scan({CpuShip(), CpuShip()}, {scan = "fof"})
            Missions:scan(CpuShip(), {scan = "simple"})
            Missions:scan({CpuShip(), CpuShip()}, {scan = "simple"})
            Missions:scan(CpuShip(), {scan = "full"})
            Missions:scan({CpuShip(), CpuShip()}, {scan = "full"})
            -- it does not error
        end)
        it("can be set to \"simple\" for asteroids", function()
            Missions:scan(Asteroid(), {scan = "simple"})
            Missions:scan({Asteroid(), Asteroid()}, {scan = "simple"})
            -- it does not error
        end)
        it("fails if it is set to \"fof\" for a non-ship", function()
            assert.has_error(function()
                Missions:scan(Asteroid(), {scan = "fof"})
            end)
        end)
        it("fails if it is set to \"fof\" for a multiple non-ship", function()
            assert.has_error(function()
                Missions:scan({Asteroid(), Asteroid()}, {scan = "fof"})
            end)
        end)
        it("fails if it is set to \"fof\" for a list where one is not a ship", function()
            assert.has_error(function()
                Missions:scan({CpuShip(), Asteroid()}, {scan = "fof"})
            end)
        end)
        it("fails if it is set to \"fof\" and function returns a non-ship", function()
            local mission = Missions:scan(function() return Asteroid() end, {scan = "fof"})
            mission:setPlayer(player)
            mission:accept()
            assert.has_error(function()
                mission:start()
            end)
        end)
        it("fails if it is set to \"fof\" and function returns multiple non-ships", function()
            local mission = Missions:scan(function() return {Asteroid(), Asteroid()} end, {scan = "fof"})
            mission:setPlayer(player)
            mission:accept()
            assert.has_error(function()
                mission:start()
            end)
        end)
        it("fails if it is set to \"fof\" and function returns a list where one is not a ship", function()
            local mission = Missions:scan(function() return {Asteroid(), CpuShip()} end, {scan = "fof"})
            mission:setPlayer(player)
            mission:accept()
            assert.has_error(function()
                mission:start()
            end)
        end)
        it("fails if it is set to \"full\" for a non-ship", function()
            assert.has_error(function()
                Missions:scan(Asteroid(), {scan = "full"})
            end)
        end)
        it("fails if it is set to \"full\" for a multiple non-ship", function()
            assert.has_error(function()
                Missions:scan({Asteroid(), Asteroid()}, {scan = "full"})
            end)
        end)
        it("fails if it is set to \"full\" for a list where one is not a ship", function()
            assert.has_error(function()
                Missions:scan({CpuShip(), Asteroid()}, {scan = "full"})
            end)
        end)
        it("fails if it is set to \"full\" and function returns a non-ship", function()
            local mission = Missions:scan(function() return Asteroid() end, {scan = "full"})
            mission:setPlayer(player)
            mission:accept()
            assert.has_error(function()
                mission:start()
            end)
        end)
        it("fails if it is set to \"full\" and function returns multiple non-ships", function()
            local mission = Missions:scan(function() return {Asteroid(), Asteroid()} end, {scan = "full"})
            mission:setPlayer(player)
            mission:accept()
            assert.has_error(function()
                mission:start()
            end)
        end)
        it("fails if it is set to \"full\" and function returns a list where one is not a ship", function()
            local mission = Missions:scan(function() return {Asteroid(), CpuShip()} end, {scan = "full"})
            mission:setPlayer(player)
            mission:accept()
            assert.has_error(function()
                mission:start()
            end)
        end)
        it("fails if it is an unknown string", function()
            assert.has_error(function()
                Missions:scan(CpuShip(), {scan = "foobar"})
            end)
        end)
    end)

    describe("getTargets(), countTargets(), getScannedTargets(), countScannedTargets(), getUnscannedTargets(), countUnscannedTargets()", function()
        it("return correct values", function()
            local target1 = CpuShip()
            local target2 = CpuShip()
            local target3 = CpuShip()
            local mission = Missions:scan({ target1, target2, target3 })
            mission:setPlayer(player)
            mission:accept()
            mission:start()

            assert.is_same(3, mission:countTargets())
            assert.is_same(3, mission:countUnscannedTargets())
            assert.is_same(0, mission:countScannedTargets())
            assert.contains_value(target1, mission:getTargets())
            assert.contains_value(target2, mission:getTargets())
            assert.contains_value(target3, mission:getTargets())
            assert.contains_value(target1, mission:getUnscannedTargets())
            assert.contains_value(target2, mission:getUnscannedTargets())
            assert.contains_value(target3, mission:getUnscannedTargets())
            assert.not_contains_value(target1, mission:getScannedTargets())
            assert.not_contains_value(target2, mission:getScannedTargets())
            assert.not_contains_value(target3, mission:getScannedTargets())

            target1:fullScannedByPlayer()
            Cron.tick(1)

            assert.is_same(3, mission:countTargets())
            assert.is_same(2, mission:countUnscannedTargets())
            assert.is_same(1, mission:countScannedTargets())
            assert.contains_value(target1, mission:getTargets())
            assert.contains_value(target2, mission:getTargets())
            assert.contains_value(target3, mission:getTargets())
            assert.not_contains_value(target1, mission:getUnscannedTargets())
            assert.contains_value(target2, mission:getUnscannedTargets())
            assert.contains_value(target3, mission:getUnscannedTargets())
            assert.contains_value(target1, mission:getScannedTargets())
            assert.not_contains_value(target2, mission:getScannedTargets())
            assert.not_contains_value(target3, mission:getScannedTargets())

            target2:fullScannedByPlayer()
            target3:fullScannedByPlayer()
            Cron.tick(1)

            assert.is_same(3, mission:countTargets())
            assert.is_same(0, mission:countUnscannedTargets())
            assert.is_same(3, mission:countScannedTargets())
            assert.contains_value(target1, mission:getTargets())
            assert.contains_value(target2, mission:getTargets())
            assert.contains_value(target3, mission:getTargets())
            assert.not_contains_value(target1, mission:getUnscannedTargets())
            assert.not_contains_value(target2, mission:getUnscannedTargets())
            assert.not_contains_value(target3, mission:getUnscannedTargets())
            assert.contains_value(target1, mission:getScannedTargets())
            assert.contains_value(target2, mission:getScannedTargets())
            assert.contains_value(target3, mission:getScannedTargets())
        end)
        it("return correct values when ships are destroyed", function()
            local target1 = CpuShip()
            local target2 = CpuShip()
            local target3 = CpuShip()
            local mission = Missions:scan({ target1, target2, target3 })
            mission:setPlayer(player)
            mission:accept()
            mission:start()

            assert.is_same(3, mission:countTargets())
            assert.is_same(3, mission:countUnscannedTargets())
            assert.is_same(0, mission:countScannedTargets())
            assert.contains_value(target1, mission:getTargets())
            assert.contains_value(target2, mission:getTargets())
            assert.contains_value(target3, mission:getTargets())
            assert.contains_value(target1, mission:getUnscannedTargets())
            assert.contains_value(target2, mission:getUnscannedTargets())
            assert.contains_value(target3, mission:getUnscannedTargets())
            assert.not_contains_value(target1, mission:getScannedTargets())
            assert.not_contains_value(target2, mission:getScannedTargets())
            assert.not_contains_value(target3, mission:getScannedTargets())

            target1:destroy()
            Cron.tick(1)

            assert.is_same(3, mission:countTargets())
            assert.is_same(2, mission:countUnscannedTargets())
            assert.is_same(0, mission:countScannedTargets())
            assert.contains_value(target1, mission:getTargets())
            assert.contains_value(target2, mission:getTargets())
            assert.contains_value(target3, mission:getTargets())
            assert.not_contains_value(target1, mission:getUnscannedTargets())
            assert.contains_value(target2, mission:getUnscannedTargets())
            assert.contains_value(target3, mission:getUnscannedTargets())
            assert.not_contains_value(target1, mission:getScannedTargets())
            assert.not_contains_value(target2, mission:getScannedTargets())
            assert.not_contains_value(target3, mission:getScannedTargets())

            target2:fullScannedByPlayer()
            Cron.tick(1)

            assert.is_same(3, mission:countTargets())
            assert.is_same(1, mission:countUnscannedTargets())
            assert.is_same(1, mission:countScannedTargets())
            assert.contains_value(target1, mission:getTargets())
            assert.contains_value(target2, mission:getTargets())
            assert.contains_value(target3, mission:getTargets())
            assert.not_contains_value(target1, mission:getUnscannedTargets())
            assert.not_contains_value(target2, mission:getUnscannedTargets())
            assert.contains_value(target3, mission:getUnscannedTargets())
            assert.not_contains_value(target1, mission:getScannedTargets())
            assert.contains_value(target2, mission:getScannedTargets())
            assert.not_contains_value(target3, mission:getScannedTargets())

            target2:destroy()
            Cron.tick(1)

            assert.is_same(3, mission:countTargets())
            assert.is_same(1, mission:countUnscannedTargets())
            assert.is_same(1, mission:countScannedTargets())
            assert.contains_value(target1, mission:getTargets())
            assert.contains_value(target2, mission:getTargets())
            assert.contains_value(target3, mission:getTargets())
            assert.not_contains_value(target1, mission:getUnscannedTargets())
            assert.not_contains_value(target2, mission:getUnscannedTargets())
            assert.contains_value(target3, mission:getUnscannedTargets())
            assert.not_contains_value(target1, mission:getScannedTargets())
            assert.contains_value(target2, mission:getScannedTargets())
            assert.not_contains_value(target3, mission:getScannedTargets())
        end)

        it("should not allow to manipulate the tables", function()
            local target1 = CpuShip()
            local target2 = CpuShip()
            local target3 = CpuShip()
            local mission = Missions:scan({ target1, target2 })
            mission:setPlayer(player)
            mission:accept()
            mission:start()


            local targets = mission:getTargets()
            table.insert(targets, target3)

            assert.is_same(2, mission:countTargets())
            assert.not_contains_value(target3, mission:getTargets())
        end)
        it("returns nil it it is called before the ships are created in the callback", function()
            local enemy1 = CpuShip()
            local enemy2 = CpuShip()
            local enemy3 = CpuShip()
            local mission = Missions:scan(function () return {enemy1, enemy2, enemy3} end)

            assert.is_nil(mission:countTargets())
            assert.is_nil(mission:countScannedTargets())
            assert.is_nil(mission:countUnscannedTargets())
            assert.is_nil(mission:getTargets())
            assert.is_nil(mission:getScannedTargets())
            assert.is_nil(mission:getUnscannedTargets())
        end)
    end)

    describe("config.onDestruction", function()
        it("is called when a target is destroyed", function()
            local target1 = CpuShip()
            local target2 = CpuShip()
            local callback1Called = 0
            local callback2Called = 0
            local mission
            mission = Missions:scan({ target1, target2 }, {onDestruction = function(callMission, callEnemy)
                assert.is_same(mission, callMission)
                if callEnemy == target1 then callback1Called = callback1Called + 1 end
                if callEnemy == target2 then callback2Called = callback2Called + 1 end
            end})

            mission:setPlayer(player)
            mission:accept()
            mission:start()

            Cron.tick(1)
            Cron.tick(1)
            Cron.tick(1)
            assert.is_same(0, callback1Called)
            assert.is_same(0, callback2Called)

            target1:destroy()
            Cron.tick(1)
            assert.is_same(1, callback1Called)
            assert.is_same(0, callback2Called)

            target2:destroy()
            Cron.tick(1)
            assert.is_same(1, callback1Called)
            assert.is_same(1, callback2Called)
        end)

        it("the unscanned targets are already updated", function()
            local target1 = CpuShip()
            local target2 = CpuShip()
            local calledArg1, calledArg2, calledUnscannedTargets, calledUnscannedTargetsCount
            local mission
            mission = Missions:scan({ target1, target2 }, {onDestruction = function(arg1, arg2)
                calledArg1 = arg1
                calledArg2 = arg2
                calledUnscannedTargets = arg1:getUnscannedTargets()
                calledUnscannedTargetsCount = arg1:countUnscannedTargets()
            end})

            mission:setPlayer(player)
            mission:accept()
            mission:start()

            Cron.tick(1)
            Cron.tick(1)

            target1:destroy()
            Cron.tick(1)
            assert.is_same(mission, calledArg1)
            assert.is_same(target1, calledArg2)
            assert.is_same(1, calledUnscannedTargetsCount)
            assert.is_same({target2}, calledUnscannedTargets)
        end)
    end)

    describe("config.onScan", function()
        it("is called each time a target is scanned", function()
            local target1 = CpuShip()
            local target2 = CpuShip()
            local target3 = CpuShip()
            local callback1Called = 0
            local callback2Called = 0
            local callback3Called = 0
            local mission
            mission = Missions:scan({ target1, target2, target3 }, {onScan = function(callMission, callTarget)
                if callTarget == target1 then callback1Called = callback1Called + 1 end
                if callTarget == target2 then callback2Called = callback2Called + 1 end
                if callTarget == target3 then callback3Called = callback3Called + 1 end
                assert.is_same(mission, callMission)
            end})

            mission:setPlayer(player)
            mission:accept()
            mission:start()

            Cron.tick(1)
            Cron.tick(1)
            Cron.tick(1)
            assert.is_same(0, callback1Called)
            assert.is_same(0, callback2Called)
            assert.is_same(0, callback3Called)

            target1:fullScannedByPlayer()
            Cron.tick(1)
            assert.is_same(1, callback1Called)
            assert.is_same(0, callback2Called)
            assert.is_same(0, callback3Called)

            target2:fullScannedByPlayer()
            target3:fullScannedByPlayer()
            Cron.tick(1)
            assert.is_same(1, callback1Called)
            assert.is_same(1, callback2Called)
            assert.is_same(1, callback3Called)
        end)

        it("is called when friend or foe is identified", function()
            local target = CpuShip()
            local callback1Called = 0
            local mission
            mission = Missions:scan(target, {scan = "fof", onScan = function(callMission, callTarget)
                callback1Called = callback1Called + 1
                assert.is_same(mission, callMission)
            end})

            mission:setPlayer(player)
            mission:accept()
            mission:start()

            Cron.tick(1)
            Cron.tick(1)
            assert.is_same(0, callback1Called)

            target:friendOrFoeIdentifiedByPlayer()
            Cron.tick(1)
            assert.is_same(1, callback1Called)

            Cron.tick(1)
            target:scannedByPlayer()
            Cron.tick(1)
            assert.is_same(1, callback1Called)

            target:fullScannedByPlayer()
            Cron.tick(1)
            assert.is_same(1, callback1Called)
        end)

        it("is called by default simple scan was run", function()
            local target = CpuShip()
            local callback1Called = 0
            local mission
            mission = Missions:scan(target, {onScan = function(callMission, callTarget)
                callback1Called = callback1Called + 1
                assert.is_same(mission, callMission)
            end})

            mission:setPlayer(player)
            mission:accept()
            mission:start()

            Cron.tick(1)
            target:friendOrFoeIdentifiedByPlayer()
            Cron.tick(1)
            assert.is_same(0, callback1Called)

            Cron.tick(1)
            target:scannedByPlayer()
            Cron.tick(1)
            assert.is_same(1, callback1Called)

            target:fullScannedByPlayer()
            Cron.tick(1)
            assert.is_same(1, callback1Called)
        end)

        it("is only called after full scan when a full scan is required", function()
            local target = CpuShip()
            local callback1Called = 0
            local mission
            mission = Missions:scan(target, {
                scan = "full",
                onScan = function(callMission, callTarget)
                    callback1Called = callback1Called + 1
                    assert.is_same(mission, callMission)
                end }
            )

            mission:setPlayer(player)
            mission:accept()
            mission:start()

            Cron.tick(1)
            Cron.tick(1)
            assert.is_same(0, callback1Called)

            target:friendOrFoeIdentifiedByPlayer()
            Cron.tick(1)
            assert.is_same(0, callback1Called)

            Cron.tick(1)
            target:scannedByPlayer()
            Cron.tick(1)
            assert.is_same(0, callback1Called)

            target:fullScannedByPlayer()
            Cron.tick(1)
            assert.is_same(1, callback1Called)
        end)
        it("the unscanned targets are already updated", function()
            local target1 = CpuShip()
            local target2 = CpuShip()
            local calledArg1, calledArg2, calledUnscannedTargets, calledUnscannedTargetsCount
            local mission
            mission = Missions:scan({ target1, target2 }, {onScan = function(arg1, arg2)
                calledArg1 = arg1
                calledArg2 = arg2
                calledUnscannedTargets = arg1:getUnscannedTargets()
                calledUnscannedTargetsCount = arg1:countUnscannedTargets()
            end})

            mission:setPlayer(player)
            mission:accept()
            mission:start()

            Cron.tick(1)
            Cron.tick(1)

            target1:fullScannedByPlayer()
            Cron.tick(1)
            assert.is_same(mission, calledArg1)
            assert.is_same(target1, calledArg2)
            assert.is_same(1, calledUnscannedTargetsCount)
            assert.is_same({target2}, calledUnscannedTargets)
        end)
    end)

    it("can run a successful mission with ships", function()
        local target1 = CpuShip()
        local target2 = CpuShip()
        local target3 = CpuShip()
        local mission
        mission = Missions:scan({ target1, target2, target3 }, {scan = "full"})

        mission:setPlayer(player)
        mission:accept()
        mission:start()

        Cron.tick(1)
        target1:fullScannedByPlayer()
        Cron.tick(1)
        assert.is_same("started", mission:getState())
        Cron.tick(1)
        target2:fullScannedByPlayer()
        Cron.tick(1)
        assert.is_same("started", mission:getState())
        Cron.tick(1)
        target3:fullScannedByPlayer()
        Cron.tick(1)
        assert.is_same("successful", mission:getState())
    end)

    it("can run a successful mission with asteroids", function()
        local target1 = Asteroid()
        local target2 = Asteroid()
        local target3 = Asteroid()
        local mission
        mission = Missions:scan({ target1, target2, target3 })

        mission:setPlayer(player)
        mission:accept()
        mission:start()

        Cron.tick(1)
        target1:scannedByPlayer()
        Cron.tick(1)
        assert.is_same("started", mission:getState())
        Cron.tick(1)
        target2:scannedByPlayer()
        Cron.tick(1)
        assert.is_same("started", mission:getState())
        Cron.tick(1)
        target3:scannedByPlayer()
        Cron.tick(1)
        assert.is_same("successful", mission:getState())
    end)

    it("can run a successful mission when not all ships are destroyed", function()
        local target1 = CpuShip()
        local target2 = CpuShip()
        local target3 = CpuShip()
        local mission
        mission = Missions:scan({ target1, target2, target3 })

        mission:setPlayer(player)
        mission:accept()
        mission:start()

        Cron.tick(1)
        target1:destroy()
        target2:destroy()
        Cron.tick(1)
        assert.is_same("started", mission:getState())
        Cron.tick(1)
        target3:fullScannedByPlayer()
        Cron.tick(1)
        assert.is_same("successful", mission:getState())
    end)

    it("fails when all ships are destroyed without having scanned one", function()
        local target1 = CpuShip()
        local target2 = CpuShip()
        local target3 = CpuShip()
        local mission
        mission = Missions:scan({ target1, target2, target3 })

        mission:setPlayer(player)
        mission:accept()
        mission:start()

        Cron.tick(1)
        target1:destroy()
        target2:destroy()
        Cron.tick(1)
        assert.is_same("started", mission:getState())
        Cron.tick(1)
        target3:destroy()
        Cron.tick(1)
        assert.is_same("failed", mission:getState())
    end)
end)