local femaleNames = {
    -- taken from https://github.com/endless-sky/endless-sky/blob/master/data/names.txt under GPLv3
    "Mary",
    "Anne",
    "Genevieve",
    "Elizabeth",
    "Shanshan",
    "Yin",
    "Lu",
    "Maria",
    "Isabella",
    "Fiona",
    "Caroline",
    "Catherine",
    "Victoria",
    "Jane",
    "Emily",
    "Nefertiti",
    "Fatima",
    "Sophia",
    "Katerina",
    "Teresa",
    "Etana",
    "Awan",
    "Xena",
    "Zoe",
    "Jane",
    "River",
    "Aletheia",
    "Sara",
    "Olympia",
    "Layla",
    "Surya",
    "Shira",
    "Anita",
    "Sato",
    "Mika",
    "Mariko",
    "Olga",
    "Jing",
    "Marianne",
    "Natalie",
    "Julia",
    "Faye",
    "Deirdre",
    "Jaina",
    "Isabel",
    "Katerina",
    "Pearl",
    "Neela",
    "Durga",
    "Devi",
    "Madhavi",
    "Amwe",
    "Nakoyan",
    "Akua",
    "Sofia",
    "Catalina",
    "Pilar",
    "Elena",
    "Athena",
    "Calypso",
}

local maleNames = {
    -- taken from https://github.com/endless-sky/endless-sky/blob/master/data/names.txt under GPLv3
    "Henry",
    "Nelson",
    "Randall",
    "Ivan",
    "James",
    "Atanu",
    "George",
    "Arthur",
    "Caspian",
    "Canute",
    "Enki",
    "Richard",
    "John",
    "William",
    "Donald",
    "Samuel",
    "Khufu",
    "Edward",
    "Sargon",
    "Amon",
    "Cyrus",
    "Darius",
    "Vipra",
    "Raja",
    "Shang",
    "Wu",
    "Xian",
    "Alan",
    "Logan",
    "Eric",
    "Malcolm",
    "Monty",
    "Dana",
    "Philip",
    "Isiah",
    "Nasser",
    "Rashid",
    "Ahmed",
    "Ari",
    "Waleed",
    "Mobutu",
    "Osamu",
    "Tarou",
    "Partha",
    "Salvador",
    "Zuhair",
    "Kenji",
    "Takeshi",
    "Hidekai",
    "Chen",
    "Mon Ping",
    "Ruslan",
    "Vladimir",
    "Fyodor",
    "Hammurabi",
    "Denton",
    "Xiang",
    "Zhong",
    "Bapu",
    "Kouadio",
    "Santiago",
    "Rafael",
    "Ignacio",
    "Bruno",
    "Martin",
    "Starbuck",
    "Xu",
}

local lastNames = {
    -- taken from https://github.com/endless-sky/endless-sky/blob/master/data/names.txt under GPLv3
    "Aristotle",
    "Aristarchus",
    "Archimedes",
    "Avogadro",
    "Abbe",
    "Alcubierre",
    "Abbott",
    "Alvarez",
    "Angstrom",
    "Anderson",
    "Bell",
    "Becquerel",
    "Bernoulli",
    "Bohr",
    "Brahe",
    "Cherenkov",
    "Coriolis",
    "Coulomb",
    "Curie",
    "Dalton",
    "Democritus",
    "Dewar",
    "Dirac",
    "Doppler",
    "Einstein",
    "Englert",
    "Euler",
    "Edison",
    "Fahrenheit",
    "Faraday",
    "Fermi",
    "Feynman",
    "Fourier",
    "Franklin",
    "Fresnel",
    "Galvani",
    "Geiger",
    "Hall",
    "Hawking",
    "Heisenberg",
    "Hertz",
    "Higgs",
    "Hooke",
    "Hubble",
    "Huygens",
    "Joule",
    "Kepler",
    "Lagrange",
    "Lebedev",
    "Leibniz",
    "Lyapunov",
    "Mach",
    "Marconi",
    "Maxwell",
    "Neumann",
    "Newcomb",
    "Newton",
    "Ohm",
    "Oppenheimer",
    "Pascal",
    "Penrose",
    "Planck",
    "Poincare",
    "Poisson",
    "Rayleigh",
    "Richter",
    "Roentgen",
    "Sagan",
    "Schroedinger",
    "Schwarzschild",
    "Tesla",
    "Watson",
    "Watt",
    "Weber",
}

personNames = {
    -- temporary interface. This is definitely not final
    getName = function()
        local gender
        local firstName
        local lastName

        if math.random(1, 2) == 1 then
            gender = "m"
            firstName = Util.random(maleNames)
        else
            gender = "f"
            firstName = Util.random(femaleNames)
        end
        lastName = Util.random(lastNames)

        return gender, firstName, lastName
    end
}