:attribute-missing: warn
:attribute-undefined: drop
:source-highlighter: coderay

:toc: left
:toclevels: 2
:icons: font

= Lively Epsilon Documentation

Lively Epsilon is a plugin framework for https://daid.github.io/EmptyEpsilon/[Empty Epsilon(EE)] that
aims to fill the space with artificial life.

If you are into writing missions this framework might help you create an intriguing universe full of life
that your crew will be eager to explore. You as a Game Master can focus on your plot lines without needing
to entertain all stations at all times.

Think about flying through the galaxy and watching traders ship goods from one station to another,
law-enforcement ships scanning ships, stations answering docking requests of NPCs or just two pilots
having a chat through comms. There is a lot to explore in that galaxy.

== Documentation

There are multiple documentations available targeted at different target audiences:

* The link:guide.html[Guide] is the document to start with if you want to get an overview of the framework
and the features it offers. It contains lots of examples that you can copy for your own scenarios.
* The link:reference.html[API Reference] describes the API of Lively Epsilon in more depth. It is automatically
generated from docblocks in the source code and thus should typically be more up-to-date than the guide.
* The link:spec.html[Specification] contains all Spec Tests that are run against the framework regularly.
It describes which of the features of the framework are intentional and you might find one or the other hidden
gem in there.

If you find anything that is wrong in here, missing documentation or typos, please open an
link:https://github.com/czenker/lively-epsilon/issues[Issue] or a link:https://github.com/czenker/lively-epsilon/pulls[Pull Request].